license = "AllRightsReserved"
issueTrackerURL = "https://github.com/ApexStudios-Dev/Issues/issues"

[[mods]]
modId = "fantasydice"
version = "${file.jarVersion}"
displayName = "FantasyDice"
credits = "Apex - Programming, Fantasy - Artist"
authors = "ApexStudios"
description = "Fantasy's Dice adds various Dungeons & Dragons inspired Dice to Minecraft."
logoFile = "logo.png"
displayURL = "https://modrinth.com/mod/fantasy-dice"

[[dependencies.fantasydice]]
modId = "neoforge"
type = "required"
versionRange = "[26.1-beta,26.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fantasydice]]
modId = "apexcore"
type = "required"
versionRange = "[26.1,26.2)"
[dependencies.fantasydice.mc-publish]
modrinth = "xl3myxch"
curseforge = "550778"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"
#[[mixins]]
#    config="META-INF/fantasydice.mixins.json"
