on:
    workflow_dispatch:
    push:
        branches: [ "**/main" ]
        paths: [ "**/src/**" ]

jobs:
    publish:
        uses: ApexStudios-Dev/.github/.github/workflows/publish-mod.yml@master
        secrets: inherit
        with:
            curseforge_id: "573867"
            modrinth_id: "hPeyEJEZ"
            release_type: "alpha"
            name: "Fantasy's Dice"
            logo: "https://raw.githubusercontent.com/ApexStudios-Dev/.github/refs/heads/master/assets/minecraft/new/fantasydice.png"
            color: "14843531" # E27E8B
            artifact_id: fantasydice
